version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: senha123  # Senha do usuário root
      MYSQL_DATABASE: treinamento    # Banco de dados a ser criado
    ports:
      - "3306:3306"                   # Expondo a porta 3306
    volumes:
      - mysql-data:/var/lib/mysql     # Persistência de dados
    networks:
      - app-network

  # Aqui você pode adicionar seu serviço Node.js mais tarde

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local